// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "AlexVonEinzbern",
            "url": "https://github.com/AlexVonEinzbern",
            "email": "mario.diaz@correounivalle.edu.co"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/go-rest-api/categories": {
            "get": {
                "description": "Search all catagories in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all Categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CategoryResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Category",
                "parameters": [
                    {
                        "description": "Category type",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CategoryCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CategoryResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/categories/active": {
            "get": {
                "description": "Search active categories in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all active Categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CategoryResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/categories/{id}": {
            "delete": {
                "description": "Delete a category by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete Category by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a category by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Category by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.CategoryResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/creditcard": {
            "get": {
                "description": "Search all credit cards in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all SearchCreditCards",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CreditCardResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a CreditCard",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create creditcard",
                "parameters": [
                    {
                        "description": "CreditCard a subcategory",
                        "name": "creditcard",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreditCardCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SubcategoryResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/creditcard/{id}": {
            "get": {
                "description": "Search CreditCard by id in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search CreditCard by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "CreditCard ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CreditCardResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a credit card by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete CreditCard by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "CreditCard ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a credit card by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update CreditCard by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "CreditCard ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.CreditCardResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/customers": {
            "get": {
                "description": "Search all customers in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all Customers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CustomerResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Customer",
                "parameters": [
                    {
                        "description": "Customer type",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CustomerCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CustomerResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/customers/{id}": {
            "get": {
                "description": "Search Customer by id in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search Customer by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CategoryResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a customer by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete Customer by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a customer by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Customer by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.CustomerResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/login": {
            "post": {
                "description": "Create a Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Login",
                "parameters": [
                    {
                        "description": "Login type",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/login/date/{date}": {
            "get": {
                "description": "Search Login by date in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search Login by Date",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2006-01-02",
                        "description": "Login date",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.LoginResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/login/{id}": {
            "get": {
                "description": "Search Login by customer id in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search Login by Customer id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Login ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.LoginResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/orderproducts": {
            "get": {
                "description": "Search all orderproducts in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all OrderProducts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OrderProductResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a OrderProduct",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create OrderProduct",
                "parameters": [
                    {
                        "description": "OrderProduct type",
                        "name": "orderproduct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderProductCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrderProductResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/orderproducts/{id}": {
            "get": {
                "description": "Search OrderProduct by id in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search OrderProduct by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "OrderProduct ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OrderProductResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/orders": {
            "get": {
                "description": "Search all orders in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all Orders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OrderResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Order",
                "parameters": [
                    {
                        "description": "Order type",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrderResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/payments": {
            "post": {
                "description": "Create a Payment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Payment",
                "parameters": [
                    {
                        "description": "Payment type",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PaymentCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PaymentResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/payments/date/{date}": {
            "get": {
                "description": "Search Payments by date in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search Payments by Date",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2006-01-02",
                        "description": "Payment date",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PaymentResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/payments/{id}": {
            "get": {
                "description": "Search Payment by id in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search Payment by Customer id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PaymentResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/products": {
            "get": {
                "description": "Search all products in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all Products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ProductResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Product",
                "parameters": [
                    {
                        "description": "Product type",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProductCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProductResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/products/active": {
            "get": {
                "description": "Search all active products in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all active Products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ProductResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/products/{id}": {
            "delete": {
                "description": "Delete a product by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a Product by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a product by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Product by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.ProductResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/shippers": {
            "get": {
                "description": "Search all shippers in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all Shippers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ShipperResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Shipper",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Shipper",
                "parameters": [
                    {
                        "description": "Shipper type",
                        "name": "shipper",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ShipperCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ShipperResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/shippers/{id}": {
            "delete": {
                "description": "Delete a shipper by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete Shipper by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Shipper ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a shipper by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Shipper by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Shipper ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.ShipperResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/subcategories": {
            "get": {
                "description": "Search all subcatagories in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all Subcategories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SubcategoryResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Subcategory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Subcategory",
                "parameters": [
                    {
                        "description": "Create a subcategory",
                        "name": "subcategory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SubcategoryCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SubcategoryResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/subcategories/active": {
            "get": {
                "description": "Search all active categories in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all active Subcategories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SubcategoryResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/subcategories/{id}": {
            "delete": {
                "description": "Delete a subcategory by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete a Subcategory by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Subcategory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a subcategory by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Subcategory by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Subcategory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.SubcategoryResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/suppliers": {
            "get": {
                "description": "Search all suppliers in the DataBase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Search all Suppliers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SupplierResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Supplier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Supplier",
                "parameters": [
                    {
                        "description": "Supplier type",
                        "name": "supplier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SupplierCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SupplierResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/go-rest-api/suppliers/{id}": {
            "delete": {
                "description": "Delete a supplier by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete Supplier by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Supplier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a supplier by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Supplier by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "cabckbalgaLJHALncas",
                        "description": "Supplier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.SupplierResponse"
                        }
                    },
                    "404": {
                        "description": "Can not find objects",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIError": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "models.CategoryCreate": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "categoryName": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "models.CategoryResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "categoryName": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "models.CreditCardCreate": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "customerID": {
                    "type": "string"
                },
                "cvv": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mm": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "yyyy": {
                    "type": "string"
                }
            }
        },
        "models.CreditCardResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "customerID": {
                    "type": "string"
                },
                "cvv": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mm": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "yyyy": {
                    "type": "string"
                }
            }
        },
        "models.CustomerCreate": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "models.CustomerResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "dni": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "models.LoginCreate": {
            "type": "object",
            "properties": {
                "customerID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "customerID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "models.OrderCreate": {
            "type": "object",
            "properties": {
                "customerID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderDate": {
                    "type": "string"
                },
                "requiredDate": {
                    "type": "string"
                },
                "shipAddress": {
                    "type": "string"
                },
                "shipCity": {
                    "type": "string"
                },
                "shipCountry": {
                    "type": "string"
                },
                "shipName": {
                    "type": "string"
                },
                "shipPostalCode": {
                    "type": "string"
                },
                "shippedDate": {
                    "type": "string"
                },
                "shipperID": {
                    "type": "string"
                }
            }
        },
        "models.OrderProductCreate": {
            "type": "object",
            "properties": {
                "discount": {
                    "type": "number"
                },
                "orderID": {
                    "type": "string"
                },
                "productID": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "unitPrice": {
                    "type": "number"
                }
            }
        },
        "models.OrderProductResponse": {
            "type": "object",
            "properties": {
                "discount": {
                    "type": "number"
                },
                "orderID": {
                    "type": "string"
                },
                "productID": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "unitPrice": {
                    "type": "number"
                }
            }
        },
        "models.OrderResponse": {
            "type": "object",
            "properties": {
                "customerID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderDate": {
                    "type": "string"
                },
                "requiredDate": {
                    "type": "string"
                },
                "shipAddress": {
                    "type": "string"
                },
                "shipCity": {
                    "type": "string"
                },
                "shipCountry": {
                    "type": "string"
                },
                "shipName": {
                    "type": "string"
                },
                "shipPostalCode": {
                    "type": "string"
                },
                "shippedDate": {
                    "type": "string"
                },
                "shipperID": {
                    "type": "string"
                }
            }
        },
        "models.PaymentCreate": {
            "type": "object",
            "properties": {
                "creditCardID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderID": {
                    "type": "string"
                }
            }
        },
        "models.PaymentResponse": {
            "type": "object",
            "properties": {
                "creditCardID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderID": {
                    "type": "string"
                }
            }
        },
        "models.ProductCreate": {
            "type": "object",
            "properties": {
                "categoryID": {
                    "type": "string"
                },
                "discontinued": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "quantityPerUnit": {
                    "type": "string"
                },
                "reorderLevel": {
                    "type": "integer"
                },
                "supplierID": {
                    "type": "string"
                },
                "unitsInStock": {
                    "type": "integer"
                },
                "unitsOnOrder": {
                    "type": "integer"
                }
            }
        },
        "models.ProductResponse": {
            "type": "object",
            "properties": {
                "categoryID": {
                    "type": "string"
                },
                "discontinued": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "quantityPerUnit": {
                    "type": "string"
                },
                "reorderLevel": {
                    "type": "integer"
                },
                "supplierID": {
                    "type": "string"
                },
                "unitsInStock": {
                    "type": "integer"
                },
                "unitsOnOrder": {
                    "type": "integer"
                }
            }
        },
        "models.ShipperCreate": {
            "type": "object",
            "properties": {
                "companyName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.ShipperResponse": {
            "type": "object",
            "properties": {
                "companyName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.SubcategoryCreate": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "categoryID": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "subCategoryName": {
                    "type": "string"
                }
            }
        },
        "models.SubcategoryResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "categoryID": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "subCategoryName": {
                    "type": "string"
                }
            }
        },
        "models.SupplierCreate": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "companyName": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "homePage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                }
            }
        },
        "models.SupplierResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "companyName": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "homePage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "go-rest-api",
	Description:      "ecommerce api-rest with basic CRUD operations (Create, Read, Update and Delete) products, suppliers, etc. Manage automatically invoice and shipping operations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
