definitions:
  models.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
  models.CategoryCreate:
    properties:
      active:
        type: boolean
      categoryName:
        type: string
      description:
        type: string
      id:
        type: string
    type: object
  models.CategoryResponse:
    properties:
      active:
        type: boolean
      categoryName:
        type: string
      description:
        type: string
      id:
        type: string
    type: object
  models.SubcategoryCreate:
    properties:
      active:
        type: boolean
      categoryID:
        type: string
      description:
        type: string
      id:
        type: string
      subCategoryName:
        type: string
    type: object
  models.SubcategoryResponse:
    properties:
      active:
        type: boolean
      categoryID:
        type: string
      description:
        type: string
      id:
        description: '`gorm:"primaryKey"`'
        type: string
      subCategoryName:
        type: string
    type: object
info:
  contact:
    email: mario.diaz@correounivalle.edu.co
    name: AlexVonEinzbern
    url: https://github.com/AlexVonEinzbern
  description: ecommerce api-rest with basic CRUD operations (Create, Read, Update
    and Delete) products, suppliers, etc. Manage automatically invoice and shipping
    operations
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: go-rest-api
  version: "1"
paths:
  /go-rest-api/category:
    post:
      consumes:
      - application/json
      description: Create a Category
      parameters:
      - description: Create a Category
        in: body
        name: subcategory
        required: true
        schema:
          $ref: '#/definitions/models.CategoryCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CategoryResponse'
        "404":
          description: Can not find objects
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Create Category
  /go-rest-api/category/{id}:
    patch:
      consumes:
      - application/json
      description: Update a category by id
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.CategoryCreate'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/models.CategoryResponse'
        "404":
          description: Can not find objects
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Update Category by id
  /go-rest-api/subcategory:
    post:
      consumes:
      - application/json
      description: Create a Subcategory
      parameters:
      - description: Create a subcategory
        in: body
        name: subcategory
        required: true
        schema:
          $ref: '#/definitions/models.SubcategoryCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SubcategoryResponse'
        "404":
          description: Can not find objects
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Create Subcategory
  /go.rest-api/category:
    get:
      consumes:
      - application/json
      description: Search all catagories in the DataBase
      parameters:
      - description: List all Categories
        in: query
        name: ListCategories
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CategoryResponse'
            type: array
        "404":
          description: Can not find objects
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Search Categories
  /go.rest-api/category/{id}:
    get:
      consumes:
      - application/json
      description: Search category by id in the DataBase
      parameters:
      - description: Category id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CategoryResponse'
            type: array
        "404":
          description: Can not find objects
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Search Category
swagger: "2.0"
